FROM node:10
WORKDIR /app

COPY ./worker/package.json ./package.json
COPY ./worker/package-lock.json ./package-lock.json
RUN npm install

COPY ./worker/index.js ./index.js
COPY ./worker/lib ./lib

CMD npm start
